TEST_VALUE:
  name: "dev_cookie"
FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a24f6d367738d00c
  FEISHU_APP_SECRET: Vg8QIE0Ce4t4DnHeUiB0DhwikqQd6qlU
MONGODB_CONFIG:
  name: "gateway"          # 自定义次数据库链接名称
  type: mongodb                      # 数据库链接类型
  url: "mongodb://47.96.124.4:27017"   # 数据库链接地址
  username: "yapipro"                   # 数据库链接用户名
  password: "yapipro1024"                 # 数据库链接密码
  database: "gateway"                # 数据库名
  entities: "mongo"                  # 自定义加载类型
  logging: false                     # 数据库打印日志
  synchronize: true                  # 是否开启同步数据表功能
MYSQL_CONFIG:
  name: "gateway"
  type: "mysql"
  host: "47.96.124.4"
  port: 3306
  username: "root"
  password: "root"
  database: "gateway"
  entities: "mysql" # 这里的命名一定要跟 MongoDB 里面的配置命名区分开
  synchronize: true